name: photology
favicon: null
layout_spectrum: 0.95585
typography_spectrum: 0.49003
title: Photology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2088d1'
    - '#0f66ad'
    - '#002665'
    - '#a3cffe'
    - '#7dbaf1'
  brandStrength: 0.8340279655531049
  lightness: 0.009636500384658575
  saturation: 0.17039971402846277
  rhythmicContrast: 0.6286603540647775
purpose: []
