name: photology
favicon: null
layout_spectrum: 0.07411
typography_spectrum: 0.49003
title: Photology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8340279655531049
  lightness: 0.009636500384658575
  saturation: 0.17039971402846277
  rhythmicContrast: 0.6286603540647775
purpose: []
